import streamlit as st
st.title("Welcome to my first app")
st.write("Hello")
name=st.text_input("Enter your name")
if st.button("Submit") :
    st.write("Hello",name)
st.chat_input("Enter email")
st.text_input("Enter your message")
st.checkbox("Check me out")
st.radio("Choose one",["Option 1","Option 2"])
st.snow()
st.balloons()
st.file_uploader("Upload a file")
st.spinner("Loading...")
st.slider("Select a value",0,100,50)
st.table({"Column 1":["A","B","C"],"Column 2":[1,2,3]}) 
st.badge("New")